#include <stdlib.h>
#include "../include/ast.h"
#include "../include/codegen.h"
#include "../include/lexer.h"
#include "../include/parser.h"
#include "../include/symtable.h"
#include "../include/token.h"
#include "../include/vm.h"
#include <stdio.h>
#include <string.h>
#include <unistd.h> // For isatty and STDIN_FILENO

/*Helper to compile and run a chunk of 
source code in the context of persistent 
Parser and VM
*/ 

void run_source(Parser *p, VM *vm, const char *src, bool is_repl){
    /*Reset the lexer for the new input line 
    without wiping the parser's symtable*/
    lexer_init(&p -> lexer, src);
    p -> current = lexer_next(&p -> lexer);

    // Capture where the code for this line starts
    int line_start_ip = vm -> code_count;
    int count = 0;
    ASTNode **stmts = parse_program(p, &count);
    
    // Only print AST for file outputs, not int the interactive REPL
    if(!is_repl && count > 0){
        printf("AST: \n");
        for(int i = 0; i < count; i++){
            print_ast(stmts[i], 0);
            printf("\n");
        }
    }

    // Generate bytecode for the parsed statement
    for(int i = 0; i < count; i++){
        codegen(stmts[i], vm, false);
    }

    // Emit a temporary OP_HALT to boundary the execution of this line
    int halt_idx = vm -> code_count;
    vm_emit(vm, OP_HALT, 0, NULL);
    if(!is_repl && vm -> start_ip == 0){
        printf("OUTPUT: \n");
    }

    // Run the VM only over the newly generated bytecode
    vm -> start_ip = line_start_ip;
    vm_run(vm);
    // Remove the temporary OP_HALT so future statements can append to code
    vm -> code_count = halt_idx;

    // Free parsed AST
    for(int i = 0; i< count; i++){
        free_ast(stmts[i]);
    }
    free(stmts);
}

// Reads the entire content of a file
char *read_file(const char* path){
    FILE *file = fopen(path, "r");
    if(!file){
        fprintf(stderr, "Error: Could not open file '%s' \n", path);
        exit(1);
    }
    fseek(file, 0, SEEK_END);
    long length = ftell(file);
    fseek(file, 0, SEEK_SET);

    char *buffer = malloc(length + 1);
    if(!buffer){
        fprintf(stderr, "Error: Memory allocation failed. \n");
        exit(1);
    }

    size_t read_bytes = fread(buffer, 1, length, file);
    buffer[read_bytes] = '\0';

    fclose(file);
    return buffer;
}

// Reads everything from stdin until EOF
char *read_stdin(void){
    size_t capacity = 1024;
    size_t length = 0;
    char *buffer = malloc(capacity);
    if(!buffer){
        fprintf(stderr, "Error: Memory allocation failed. \n");
        exit(1);
    }

    int c;
    while((c = getchar()) != EOF){
        if(length + 1 >= capacity){
            capacity *= 2;
            buffer = realloc(buffer,capacity);
            if(!buffer){
                fprintf(stderr, "Error: Memory allocation failed. \n");
                exit(1);
            }
        }
        buffer[length++] = c;
    }
    buffer[length] = '\0';
    return buffer;
}

int main(int argc, char **argv){
    Parser p;
    VM vm;
    vm_init(&vm);

    // Initialize the parser with an empty string to set up its symbol table
    parser_init(&p, "");

    if(argc > 2){
        fprintf(stderr, "Usage: %s [file.toy]\n", argv[0]);
        return 1;
    }

    if(argc == 2){
        // Mode1 : Read and run a source file
        char *src = read_file(argv[1]);
        run_source(&p, &vm, src, false);
        free(src);
    }else {
        // Mode 2: If input is piped (e.g. echo "code" | compiler), read STDIN
        if(!isatty(STDIN_FILENO)){
            char *src = read_stdin();
            run_source(&p, &vm, src, false);
            free(src);
        }else {
            // Mode 3: Interactive REPL Terminal
            printf("Toy Compiler REPL (Day 15)\n"
                     "Type code and press Enter. Type 'exit' to quit.\n\n"
                    );
                    char line[1024];
                    while(1){
                        printf("toy> ");
                        if(!fgets(line, sizeof(line), stdin)){
                            break;
                        }

                        // Strip trailing newline character
                        line[strcspn(line, "\n")] = '\0';
                        // Skip empty entries
                        if(line[0] == '\0'){
                            continue;
                        }

                        if(strcmp(line, "exit") == 0){
                            break;
                        }

                        // Parse, compile and run this statment interactively
                        run_source(&p, &vm, line, true);
                    }
        }
    }
    return 0;
}